name: 🔫 Trigger Workflow

on:
  schedule:
    # Execute everyday at 06:00am (UTC+2)
    - cron: "00 1 * * *"

  workflow_dispatch:
    inputs:
      workflow_selection:
        description: 'Select workflow(s) to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - workflow-1
          - workflow-2
      environment:
        description: 'Select environment'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV

jobs:
  run-positive-workflow:
    name: Workflow 1
    if: >-
      always() &&
      (github.event_name == 'schedule' ||
       github.event.inputs.workflow_selection == 'all' ||
       github.event.inputs.workflow_selection == 'workflow-1')
    uses: ./.github/workflows/positive-workflow.yml
    with:
      environment: ${{ github.event.inputs.environment || 'DEV' }}
      postman_collection_id: 4032962-0e025640-bfff-4a7f-bb8e-6a78089b9de7
      postman_environment_id: 4032962-d4db2ed5-980b-4830-9e5a-870775472a2c
    secrets:
      postman_api_key: ${{ secrets.POSTMAN_API_KEY }}

  run-negative-workflow:
    name: Workflow 2
    if: >-
      always() &&
      (github.event_name == 'schedule' ||
       github.event.inputs.workflow_selection == 'all' ||
       github.event.inputs.workflow_selection == 'workflow-2')
    uses: ./.github/workflows/negative-workflow.yml
    with:
      environment: ${{ github.event.inputs.environment || 'DEV' }}
      postman_collection_id: 4032962-0e025640-bfff-4a7f-bb8e-6a78089b9de7
      postman_environment_id: 4032962-d4db2ed5-980b-4830-9e5a-870775472a2c
    secrets:
      postman_api_key: ${{ secrets.POSTMAN_API_KEY }}
